source 'https://rubygems.org'

gem 'rake'
gem 'activerecord'
gem 'minitest'
gem 'pg'
gem 'iso_country_codes'
gem 'simplecov'
gem 'awesome_print'
gem 'pry'
gem 'builder'
gem 'hstore_translate'
gem 'rr'
gem 'shoulda-matchers'

